### ISSUE TITLE
希望增加Eink模式

### ISSUE THREAD

**Issue by Debatrix** [gedoor/MyBookshelf#190]
希望增加Eink模式 app配色方案变为黑白 关闭所有动画

此外想问下这个app能支持的最低的Android版本是多少 我手上甚至还有维持在Android2.3的中古电纸书

**Comment by liaong** [comment]
配色和动画都不是什么问题，主要是墨水屏字迹残留。只要能有个动画模式是翻页先清空文字再显示新一页的文字就行了，当然，如果是刷新率比较低的水墨屏设备可能还是会有一定的字迹残留。

**Comment by huhd** [comment]
用了EINK模式，结果阅读背景变成了深灰色，而且设置背景色就crash。取消EINK模式背景色才会白色。
java.lang.OutOfMemoryError: Failed to allocate a 14520012 byte allocation with 6352632 free bytes and 6MB until OOM
I/f       (15244):      at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
I/f       (15244):      at android.graphics.Bitmap.nativeCreate(Native Method)
I/f       (15244):      at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
I/f       (15244):      at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
I/f       (15244):      at android.graphics.Bitmap.createBitmap(Bitmap.java:756)
I/f       (15244):      at com.kunfei.bookshelf.widget.page.animation.HorizonPageAnim.<init>(HorizonPageAnim.java:37)
I/f       (15244):      at com.kunfei.bookshelf.widget.page.animation.NonePageAnim.<init>(NonePageAnim.java:13)
I/f       (15244):      at com.kunfei.bookshelf.widget.page.PageView.setPageMode(PageView.java:135)
I/f       (15244):      at com.kunfei.bookshelf.widget.page.PageLoader.refreshUi(PageLoader.java:363)

**Comment by huhd** [comment]
在sony dpt-rp1电子书里，查找书名的时候，查找结果不可见，触摸可以点到结果，就是结果出来了，但是屏幕显示的颜色和背景色一样了？然后点返回的话，结果会闪现一下，然后就回到书架了。还有，查找输入的话，只调用了英文软输入，不让使用中文软输入。
