### ISSUE TITLE
rulebookname rulebookauthor有问题？

### ISSUE THREAD

**Issue by daiaji** [gedoor/MyBookshelf#235]
rulebookname rulebookauthor是不是已经是无效值了？
我填和不填 书源调试都能获取到这两个值
那么为什么不干脆用rulesearchauthor的值替代rulecoverurl

还有就是因为类似的缘故
如果填写了rulebookauthor
详情页点击作者名字搜索书籍的话
app会崩掉
不填写就能点击作者名字正常搜书
但是老书源都是填了rulebookauthor的吧

**Comment by Antecer** [comment]
书籍信息解析流程:
1.从search页查找书籍信息
2.从详情页查找search页没有的信息
也就是说,当你的搜索规则匹配到的内容,详情页的规则就不会再次匹配了.

**Comment by daiaji** [comment]
@Antecer 所以为什么要重新获取封面？

**Comment by Antecer** [comment]
填写rulebookauthor会导致APP崩溃?我的没出现这种现象啊.
能讲一下你的重现故障流程嘛?

**Comment by daiaji** [comment]
> 填写rulebookauthor会导致APP崩溃?我的没出现这种现象啊.
> 能讲一下你的重现故障流程嘛?

很简单 比如这个
```
{
  "bookSourceGroup": "正版",
  "bookSourceName": "起点中文网💯",
  "bookSourceUrl": "https://www.qidian.com",
  "enable": true,
  "httpUserAgent": "",
  "loginUrl": "",
  "ruleBookAuthor": "class.book-info@tag.h1@tag.span@tag.a@text",
  "ruleBookContent": "class.read-content@tag.p@text",
  "ruleBookKind": "",
  "ruleBookLastChapter": "",
  "ruleBookName": "class.book-info@tag.h1@tag.em@text",
  "ruleBookUrlPattern": "",
  "ruleChapterList": "class.volume-wrap@class.volume@tag.ul@tag.li",
  "ruleChapterName": "tag.a@text",
  "ruleChapterUrl": "",
  "ruleChapterUrlNext": "",
  "ruleContentUrl": "tag.a@href",
  "ruleContentUrlNext": "",
  "ruleCoverUrl": "",
  "ruleFindUrl": "月票榜::https://www.qidian.com/rank/yuepiao?page=searchPage&&推荐榜::https://www.qidian.com/rank/recom?style=1&page=searchPage&&强推榜::https://www.qidian.com/book/strongrec?style=1&page=searchPage&&收藏榜::https://www.qidian.com/rank/collect?style=1&page=searchPage&&三江榜::https://www.qidian.com/book/sanjiang?style=1&page=searchPage&&点击榜::https://www.qidian.com/rank/newvipclick?style=1&page=searchPage&&打赏榜::https://www.qidian.com/rank/vipreward?style=1&page=searchPage&&热销榜::https://www.qidian.com/rank/hotsales?style=1&page=searchPage&&更新榜::https://www.qidian.com/rank/vipup?style=1&page=searchPage&&完　本::https://www.qidian.com/rank/fin?style=1&page=searchPage&&玄　幻::https://www.qidian.com/rank/click?style=1&dateType=3&chn=21&page=searchPage&&奇　幻::https://www.qidian.com/rank/click?style=1&dateType=3&chn=1&page=searchPage&&武　侠::https://www.qidian.com/rank/click?style=1&dateType=3&chn=2&page=searchPage&&仙　侠::https://www.qidian.com/rank/click?style=1&dateType=3&chn=22&page=searchPage&&都　市::https://www.qidian.com/rank/click?style=1&dateType=3&chn=4&page=searchPage&&现　实::https://www.qidian.com/rank/click?style=1&dateType=3&chn=15&page=searchPage&&军　事::https://www.qidian.com/rank/click?style=1&dateType=3&chn=6&page=searchPage&&历　史::https://www.qidian.com/rank/click?style=1&dateType=3&chn=5&page=searchPage&&游　戏::https://www.qidian.com/rank/click?style=1&dateType=3&chn=7&page=searchPage&&体　育::https://www.qidian.com/rank/click?style=1&dateType=3&chn=8&page=searchPage&&科　幻::https://www.qidian.com/rank/click?style=1&dateType=3&chn=9&page=searchPage&&灵　异::https://www.qidian.com/rank/click?style=1&dateType=3&chn=10&page=searchPage&&二次元::https://www.qidian.com/rank/click?style=1&dateType=3&chn=12&page=searchPage&&签约作家新书榜::https://www.qidian.com/rank/signnewbook?style=1&&公众作者新书榜::https://www.qidian.com/rank/pubnewbook?style=1&page=searchPage&&新人签约新书榜::https://www.qidian.com/rank/newsign?style=1&page=searchPage&&新人作者新书榜::https://www.qidian.com/rank/newauthor?style=1&page=searchPage&&本周会员点击榜::https://www.qidian.com/rank/click?style=1&page=searchPage",
  "ruleIntroduce": "class.book-intro@tag.p@text",
  "ruleSearchAuthor": "class.book-mid-info@class.author@tag.a.0@text|tag.a.2@text|tag.span@text",
  "ruleSearchCoverUrl": "class.book-img-box@tag.img@src",
  "ruleSearchKind": "class.book-mid-info@class.author@tag.a.1@text|tag.a.0@text",
  "ruleSearchLastChapter": "class.book-mid-info@class.update@tag.a.0@text#最新更新",
  "ruleSearchList": "class.book-img-text@tag.ul@tag.li|class.strongrec-list book-list-wrap@class.book-list@tag.li",
  "ruleSearchName": "class.book-mid-info@tag.h4@tag.a@text|tag.a.1@text",
  "ruleSearchNoteUrl": "class.book-mid-info@tag.h4@tag.a@href|tag.a.1@href",
  "ruleSearchUrl": "https://www.qidian.com/search?kw=searchKey&page=searchPage",
  "serialNumber": 0,
  "weight": 0
}
```
随便找本书 详情页点作者名就会FC
不填屁事都没有

![image](https://i.imgur.com/mg7I0Sm.gif)
gif贴不了是闹哪样？

**Comment by Antecer** [comment]
估计是随着阅读更新,一些老书源就过时了,于是出现了兼容性问题.
起点的话,你用这个吧,直接APP内选择网络导入就行了:
`https://booksources.github.io`

**Comment by daiaji** [comment]
> 估计是随着阅读更新,一些老书源就过时了,于是出现了兼容性问题.
> 起点的话,你用这个吧,直接APP内选择网络导入就行了:
> `https://booksources.github.io`

问题是我后来重做了一个书源……
然后也有这问题

**Comment by gedoor** [comment]
FC可以把日志贴出来我看看,日志以cache文件夹

**Comment by daiaji** [comment]
@Antecer @gedoor 更可乐的是 @Antecer 发给我的源用起点
按照gif操作一遍也会崩溃

**Comment by Antecer** [comment]
那可能这个BUG与你的机型或者系统有关了.

**Comment by daiaji** [comment]
@Antecer 没法复现吗？
我换了台OPPO的手机也一样fc
8.0系统

**Comment by gedoor** [comment]
发日志啊,android\data\com.gedoor里找

**Comment by Antecer** [comment]
已经复现了,之前没理解对意思.
以为是书架的详情页点作者搜索,这个是没问题的.

有问题的是,在搜索结果列表内,点开详情页,再点击作者名就会崩溃.

**Comment by daiaji** [comment]
@gedoor 

```
BOARD=msm8998 CPU_ABI2= HOST=ilclbld32 versionName=2.19.042009 IS_TREBLE_ENABLED=false SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@dd7d1a7 CPU_ABI=arm64-v8a PERMISSIONS_REVIEW_REQUIRED=false IS_USERDEBUG=false DISPLAY=OPXS27.109-52-12 SUPPORTED_ABIS=[Ljava.lang.String;@4ef5654 FINGERPRINT=motorola/nash/nash:8.0.0/OPXS27.109-52-12/16:user/release-keys PRODUCT=nash ID=OPXS27.109-52-12 TYPE=user SERIAL=ZY224HLGQ4 IS_CONTAINER=false IS_ENG=false DEVICE=nash TIME=1547146002000 IS_USER=true MODEL=Moto Z (2) MANUFACTURER=motorola USER=hudsoncm MOTO_BUILD_DISPLAY=OPXS27.109-52-12 versionCode=14621 BRAND=motorola SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@3c0aa66 HARDWARE=qcom IS_DEBUGGABLE=false BOOTLOADER=MBM-3.0-nash_sprint-ab41784-180828 RADIO=unknown TAG=Build UNKNOWN=unknown IS_EMULATOR=false TAGS=release-keys java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 6(offset:0).state:7 androidx.recyclerview.widget.RecyclerView{45ccbc5 VFED.V... .F....ID 0,0-1440,2240 #7f0901c9 app:id/recycler_view}, adapter:com.kunfei.bookshelf.view.adapter.SearchBookAdapter@162c3cb, layout:androidx.recyclerview.widget.LinearLayoutManager@8b767a8, context:com.kunfei.bookshelf.view.activity.SearchBookActivity@ded3234 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6023) 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5958) 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5954) 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2226) 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557) 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517) 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612) 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3941) 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3705) 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4260) 	at android.view.View.layout(View.java:19602) 	at android.view.ViewGroup.layout(ViewGroup.java:6057) 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323) 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261) 	at android.view.View.layout(View.java:19602) 	at android.view.ViewGroup.layout(ViewGroup.java:6057) 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791) 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635) 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544) 	at android.view.View.layout(View.java:19602) 	at android.view.ViewGroup.layout(ViewGroup.java:6057) 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323) 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261) 	at android.view.View.layout(View.java:19602) 	at android.view.ViewGroup.layout(ViewGroup.java:6057) 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080) 	at android.view.View.layout(View.java:19602) 	at android.view.ViewGroup.layout(ViewGroup.java:6057) 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791) 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635) 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544) 	at android.view.View.layout(View.java:19602) 	at android.view.ViewGroup.layout(ViewGroup.java:6057) 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323) 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261) 	at android.view.View.layout(View.java:19602) 	at android.view.ViewGroup.layout(ViewGroup.java:6057) 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791) 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635) 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544) 	at android.view.View.layout(View.java:19602) 	at android.view.ViewGroup.layout(ViewGroup.java:6057) 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323) 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261) 	at android.view.View.layout(View.java:19602) 	at android.view.ViewGroup.layout(ViewGroup.java:6057) 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791) 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635) 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544) 	at android.view.View.layout(View.java:19602) 	at android.view.ViewGroup.layout(ViewGroup.java:6057) 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323) 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261) 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:758) 	at android.view.View.layout(View.java:19602) 	at android.view.ViewGroup.layout(ViewGroup.java:6057) 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2512) 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2228) 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1414) 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6827) 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911) 	at android.view.Choreographer.doCallbacks(Choreographer.java:723) 	at android.view.Choreographer.doFrame(Choreographer.java:658) 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897) 	at android.os.Handler.handleCallback(Handler.java:789) 	at android.os.Handler.dispatchMessage(Handler.java:98) 	at android.os.Looper.loop(Looper.java:164) 	at android.app.ActivityThread.main(ActivityThread.java:6592) 	at java.lang.reflect.Method.invoke(Native Method) 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769) 
```

**Comment by daiaji** [comment]
@Antecer 愕谔，你没看我录的gif吗？

**Comment by Antecer** [comment]
之前没加载出来

**Comment by daiaji** [comment]
@Antecer @gedoor  还发现了一个问题 搜索书籍时（没获得结果前）中断网络（比如网络屌差 或者断开流量 wifi）会显示“未搜索到内容”和一个“重试”按钮这时候点重试并不会重新发起搜索

**Comment by Antecer** [comment]
点击作者名搜索会Crash的问题已经修复,等下一次APP更新就好了.

**Comment by daiaji** [comment]
> @Antecer @gedoor 还发现了一个问题 搜索书籍时（没获得结果前）中断网络（比如网络屌差 或者断开流量 wifi）会显示“未搜索到内容”和一个“重试”按钮这时候点重试并不会重新发起搜索
![Screenshot_20190423-011743](https://user-images.githubusercontent.com/25875791/56515361-5516b100-656a-11e9-9a52-6edaf51b6b26.png)

这边提到的问题新开个Issues？

**Comment by gedoor** [comment]
下版本解决

**Comment by daiaji** [comment]
@gedoor 👌
